# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1

matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
        - NUMPYSPEC=numpy
      before_install:
        - pip install pep8==1.6.2
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes pysapprox demo | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 pysapprox demo
    - os: linux
      python: 3.6
      env:
        - NUMPYSPEC=numpy
        - USE_WHEEL=1
      before_install:
        - pip install scipy
    - os: linux
      python: 3.4
      env:
        - NUMPYSPEC=numpy
        - USE_SDIST=1
      before_install:
        - pip install scipy
    - os: linux
      python: 2.7
      env:
        - NUMPYSPEC="numpy==1.9.3"
      before_install:
        - pip install scipy
    - os: linux
      python: 3.5
      env:
        - NUMPYSPEC=numpy
        - REFGUIDE_CHECK=1  # run doctests only
      before_install:
        - pip install scipy
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env:
        - NUMPYSPEC=numpy
        - TRAVIS_PYTHON_VERSION=3.5
      before_install:
        - pip install scipy

cache: pip

before_install:
  - uname -a
  - df -h
  - ulimit -a
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source util/travis_osx_install.sh; fi
  - ccache -s
  - which python; python --version
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install $NUMPYSPEC
  - pip install Cython matplotlib nose coverage codecov futures scipy
  - set -o pipefail 
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install sphinx numpydoc
    fi

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        pip wheel . -v
        pip install pySApprox*.whl -v
        pushd demo
        nosetests pysapprox
        popd
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local pysapprox
        pushd dist
        pip install pySApprox* -v
        nosetests pysapprox
        popd
    elif [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install -e . -v
        python util/refguide_check.py --doctests
    else
        CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        nosetests build/lib/ --tests pysapprox/tests
    fi

after_success:
  - codecov
  # Travis CI has old gcov, needs object dir explicitly specified
  - bash <(curl -s https://codecov.io/bash)